### ISSUE TITLE
Add links from API docs to source. Checklist.

### ISSUE THREAD

**Issue by Devinsuit** [d3/d3#2936]
# Things to do (https://github.com/d3/d3/issues/2922)

- [x] Arrays (d3-array)
- [x] Axes (d3-axis)
- [x] Brushes (d3-brush)
- [x] Chords (d3-chord)
- [x] Collections (d3-collection)
- [x] Colors (d3-color)
- [x] Dispatches (d3-dispatch)
- [x] Dragging (d3-drag)
- [x] Delimiter-Separated Values (d3-dsv)
- [x] Easings (d3-ease)
- [x] Forces (d3-force)
- [x] Number Formats (d3-format)
- [x] Geographies (d3-geo)
- [x] Hierarchies (d3-hierarchy)
- [x] Interpolators (d3-interpolate)
- [x] Paths (d3-path)
- [x] Polygons (d3-polygon)
- [x] Quadtrees (d3-quadtree)
- [x] Queues (d3-queue)
- [x] Random Numbers (d3-random)
- [x] Requests (d3-request)
- [x] Scales (d3-scale)
- [x] Selections (d3-selection)
- [x] Shapes (d3-shape)
- [x] Time Formats (d3-time-format)
- [x] Time Intervals (d3-time)
- [x] Timers (d3-timer)
- [x] Transitions (d3-transition)
- [x] Voronoi Diagrams (d3-voronoi)
- [x] Zooming (d3-zoom)

Choose your module, leave a comment and add chevrons next to the method name in README.md like this:

>[#](https://github.com/d3/d3-array/blob/master/README.md#min) d3.min(array[, accessor]) [<>](https://github.com/d3/d3-array/blob/master/src/min.js "Source")

Returns the minimum value in the given array using natural order. If the array is empty, returns undefined. An optional accessor function may be specified, which is equivalent to calling array.map(accessor) before computing the minimum value.

**Comment by Devinsuit** [comment]
Axes (d3-axis)

**Comment by Devinsuit** [comment]
Arrays (d3-array).

**Comment by Devinsuit** [comment]
Brushes (d3-brush) done! https://github.com/d3/d3-brush/pull/12

**Comment by Devinsuit** [comment]
Chords (d3-chord).

**Comment by Devinsuit** [comment]
Arrays (d3-array).

**Comment by Devinsuit** [comment]
Collections (d3-collection).

**Comment by Devinsuit** [comment]
Colors (d3-color).

**Comment by Devinsuit** [comment]
Dispatches (d3-dispatch).

**Comment by Devinsuit** [comment]
Dragging (d3-drag).

**Comment by Devinsuit** [comment]
Delimiter-Separated Values (d3-dsv).

**Comment by Devinsuit** [comment]
Easings (d3-ease).

**Comment by mef** [comment]
Timers (d3-timer) ongoing  d3/d3-timer#15

**Comment by mef** [comment]
Random Numbers (d3-random) ongoing d3/d3-random#16

**Comment by Devinsuit** [comment]
Forces (d3-force).

**Comment by Devinsuit** [comment]
Number Formats (d3-format).

**Comment by Devinsuit** [comment]
@AboorvaDevarajan d3/d3-polygon

**Comment by Devinsuit** [comment]
Geographies (d3-geo).

**Comment by Devinsuit** [comment]
Queues (d3-queue).

**Comment by Devinsuit** [comment]
Quadtrees (d3-quadtree).

**Comment by Devinsuit** [comment]
Paths (d3-path).

**Comment by Devinsuit** [comment]
Hierarchies (d3-hierarchy).

**Comment by Devinsuit** [comment]
Interpolators (d3-interpolate). Done!

**Comment by Devinsuit** [comment]
Requests (d3-request). Done!

**Comment by Devinsuit** [comment]
Zooming (d3-zoom). Done!

**Comment by Devinsuit** [comment]
Voronoi Diagrams (d3-voronoi). Done!

**Comment by Devinsuit** [comment]
Transitions (d3-transition). Done!

**Comment by Devinsuit** [comment]
Time Intervals (d3-time). Done!

**Comment by Devinsuit** [comment]
Shapes (d3-shape). Done!

**Comment by mef** [comment]
Time Formats (d3-time-format). Ongoing. d3/d3-time-format#21

**Comment by Devinsuit** [comment]
Selections (d3-selection). Done!

**Comment by Devinsuit** [comment]
Scales (d3-scale). Done! The last one!

**Comment by Devinsuit** [comment]
It's been great working with you!

**Comment by Devinsuit** [comment]
- [ ] 
- [ ]
- [ ] 
- [ ]
- [ ]
- [ ]
