### ISSUE TITLE
VitePress documentation tracking issue

### ISSUE THREAD

**Issue by mbostock** [d3/d3#3655]
TODO

- [x] GitHub actions for publishing
- [ ] copy static files (e.g., d3.v3.js) for backwards-compatible hosting
- [ ] [index.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/index.md)
- [ ] [what-is-d3.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/what-is-d3.md)
- [ ] [why-d3.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/why-d3.md)
- [x] [getting-started.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/getting-started.md)
- [x] [api.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/api.md)
- [x] [community.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/community.md)
- [x] [d3-array.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-array.md)
- [x] [d3-array/add.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-array/add.md)
- [x] [d3-array/bin.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-array/bin.md)
- [x] [d3-array/bisect.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-array/bisect.md)
- [x] [d3-array/blur.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-array/blur.md)
- [x] [d3-array/group.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-array/group.md)
- [x] [d3-array/intern.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-array/intern.md)
- [x] [d3-array/sets.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-array/sets.md)
- [x] [d3-array/sort.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-array/sort.md)
- [x] [d3-array/summarize.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-array/summarize.md)
- [x] [d3-array/ticks.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-array/ticks.md)
- [x] [d3-array/transform.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-array/transform.md)
- [x] [d3-axis.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-axis.md)
- [x] [d3-brush.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-brush.md)
- [x] [d3-chord.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-chord.md)
- [x] [d3-chord/chord.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-chord/chord.md)
- [x] [d3-chord/ribbon.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-chord/ribbon.md)
- [x] [d3-color.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-color.md)
- [x] [d3-contour.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-contour.md)
- [x] [d3-contour/contour.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-contour/contour.md)
- [x] [d3-contour/density.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-contour/density.md)
- [x] [d3-delaunay.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-delaunay.md)
- [x] [d3-delaunay/delaunay.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-delaunay/delaunay.md)
- [x] [d3-delaunay/voronoi.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-delaunay/voronoi.md)
- [x] [d3-dispatch.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-dispatch.md)
- [x] [d3-drag.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-drag.md)
- [x] [d3-dsv.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-dsv.md)
- [x] [d3-ease.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-ease.md)
- [x] [d3-fetch.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-fetch.md)
- [x] [d3-force.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-force.md)
- [x] [d3-force/simulation.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-force/simulation.md)
- [x] [d3-force/center.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-force/center.md)
- [x] [d3-force/collide.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-force/collide.md)
- [x] [d3-force/link.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-force/link.md)
- [x] [d3-force/many-body.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-force/many-body.md)
- [x] [d3-force/position.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-force/position.md)
- [x] [d3-format.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-format.md)
- [x] [d3-geo.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-geo.md)
- [x] [d3-geo/azimuthal.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-geo/azimuthal.md)
- [x] [d3-geo/conic.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-geo/conic.md)
- [x] [d3-geo/cylindrical.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-geo/cylindrical.md)
- [x] [d3-geo/math.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-geo/math.md)
- [x] [d3-geo/path.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-geo/path.md)
- [x] [d3-geo/projection.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-geo/projection.md)
- [x] [d3-geo/shape.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-geo/shape.md)
- [x] [d3-geo/stream.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-geo/stream.md)
- [x] [d3-hierarchy.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-hierarchy.md)
- [x] [d3-hierarchy/hierarchy.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-hierarchy/hierarchy.md)
- [x] [d3-hierarchy/stratify.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-hierarchy/stratify.md)
- [x] [d3-hierarchy/tree.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-hierarchy/tree.md)
- [x] [d3-hierarchy/cluster.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-hierarchy/cluster.md)
- [x] [d3-hierarchy/partition.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-hierarchy/partition.md)
- [x] [d3-hierarchy/pack.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-hierarchy/pack.md)
- [x] [d3-hierarchy/treemap.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-hierarchy/treemap.md)
- [x] [d3-interpolate.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-interpolate.md)
- [x] [d3-interpolate/value.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-interpolate/value.md)
- [x] [d3-interpolate/color.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-interpolate/color.md)
- [x] [d3-interpolate/transform.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-interpolate/transform.md)
- [x] [d3-interpolate/zoom.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-interpolate/zoom.md)
- [x] [d3-path.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-path.md)
- [x] [d3-polygon.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-polygon.md)
- [x] [d3-quadtree.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-quadtree.md)
- [x] [d3-random.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-random.md)
- [x] [d3-scale-chromatic.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale-chromatic.md)
- [x] [d3-scale-chromatic/categorical.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale-chromatic/categorical.md)
- [x] [d3-scale-chromatic/cyclical.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale-chromatic/cyclical.md)
- [x] [d3-scale-chromatic/diverging.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale-chromatic/diverging.md)
- [x] [d3-scale-chromatic/sequential.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale-chromatic/sequential.md)
- [x] [d3-scale.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale.md)
- [x] [d3-scale/linear.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/linear.md)
- [x] [d3-scale/time.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/time.md)
- [x] [d3-scale/pow.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/pow.md)
- [x] [d3-scale/log.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/log.md)
- [x] [d3-scale/symlog.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/symlog.md)
- [x] [d3-scale/ordinal.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/ordinal.md)
- [x] [d3-scale/band.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/band.md)
- [x] [d3-scale/point.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/point.md)
- [x] [d3-scale/sequential.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/sequential.md)
- [x] [d3-scale/diverging.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/diverging.md)
- [x] [d3-scale/quantile.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/quantile.md)
- [x] [d3-scale/quantize.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/quantize.md)
- [x] [d3-scale/threshold.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-scale/threshold.md)
- [x] [d3-selection.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-selection.md)
- [x] [d3-selection/selecting.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-selection/selecting.md)
- [x] [d3-selection/modifying.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-selection/modifying.md)
- [x] [d3-selection/joining.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-selection/joining.md)
- [x] [d3-selection/events.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-selection/events.md)
- [x] [d3-selection/control-flow.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-selection/control-flow.md)
- [x] [d3-selection/locals.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-selection/locals.md)
- [x] [d3-selection/namespaces.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-selection/namespaces.md)
- [x] [d3-shape.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-shape.md)
- [x] [d3-shape/arc.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-shape/arc.md)
- [x] [d3-shape/area.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-shape/area.md)
- [x] [d3-shape/curve.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-shape/curve.md)
- [x] [d3-shape/line.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-shape/line.md)
- [x] [d3-shape/link.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-shape/link.md)
- [x] [d3-shape/pie.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-shape/pie.md)
- [x] [d3-shape/stack.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-shape/stack.md)
- [x] [d3-shape/symbol.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-shape/symbol.md)
- [x] [d3-shape/radial-area.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-shape/radial-area.md)
- [x] [d3-shape/radial-line.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-shape/radial-line.md)
- [x] [d3-shape/radial-link.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-shape/radial-link.md)
- [x] [d3-time-format.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-time-format.md)
- [x] [d3-time.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-time.md)
- [x] [d3-timer.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-timer.md)
- [x] [d3-transition.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-transition.md)
- [x] [d3-transition/selecting.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-transition/selecting.md)
- [x] [d3-transition/modifying.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-transition/modifying.md)
- [x] [d3-transition/timing.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-transition/timing.md)
- [x] [d3-transition/control-flow.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-transition/control-flow.md)
- [x] [d3-zoom.md](https://github.com/d3/d3/blob/mbostock/vitepress/docs/d3-zoom.md)

Ref. #3654

**Comment by ShatilKhan** [comment]
Hi @mbostock ,
I would like to help out in this documentation.
I really like D3 & have several Data Viz projects with & enjoyed it very much, I would love to work on this so can you assign me please?
