### ISSUE TITLE
Tracking issue for D3 gallery examples style

### ISSUE THREAD

**Issue by mbostock** [d3/d3#3685]
d3:

- [ ] [Animated treemap](https://observablehq.com/@d3/animated-treemap)
- [ ] [Arc diagram](https://observablehq.com/@d3/arc-diagram)
- [x] [Area with missing data](https://observablehq.com/@d3/area-chart-missing-data/2)
- [x] [Area chart](https://observablehq.com/@d3/area-chart/2)
- [ ] [Band chart](https://observablehq.com/@d3/band-chart)
- [ ] [Bar chart race](https://observablehq.com/@d3/bar-chart-race)
- [x] [Bar chart](https://observablehq.com/@d3/bar-chart/2)
- [ ] [Mirrored beeswarm](https://observablehq.com/@d3/beeswarm-mirrored/2)
- [x] [Beeswarm](https://observablehq.com/@d3/beeswarm/2)
- [ ] [Bivariate choropleth](https://observablehq.com/@d3/bivariate-choropleth)
- [x] [Bollinger bands](https://observablehq.com/@d3/bollinger-bands/2)
- [ ] [Box plot](https://observablehq.com/@d3/box-plot)
- [ ] [Brushable scatterplot matrix](https://observablehq.com/@d3/brushable-scatterplot-matrix)
- [ ] [Brushable scatterplot](https://observablehq.com/@d3/brushable-scatterplot)
- [x] [Bubble chart](https://observablehq.com/@d3/bubble-chart/2)
- [ ] [Bubble map](https://observablehq.com/@d3/bubble-map)
- [x] [Calendar](https://observablehq.com/@d3/calendar/2)
- [ ] [Candlestick chart](https://observablehq.com/@d3/candlestick-chart/2)
- [ ] [Cascaded treemap](https://observablehq.com/@d3/cascaded-treemap)
- [ ] [Change line chart](https://observablehq.com/@d3/change-line-chart/2)
- [ ] [Chord dependency diagram](https://observablehq.com/@d3/chord-dependency-diagram)
- [ ] [Chord diagram](https://observablehq.com/@d3/chord-diagram)
- [x] [Choropleth](https://observablehq.com/@d3/choropleth/2)
- [ ] [Clipped map tiles](https://observablehq.com/@d3/clipped-map-tiles)
- [ ] [Cluster dendrogram](https://observablehq.com/@d3/cluster-dendrogram)
- [ ] [Collapsible tree](https://observablehq.com/@d3/collapsible-tree)
- [ ] [Color legend](https://observablehq.com/@d3/color-legend)
- [ ] [Color schemes](https://observablehq.com/@d3/color-schemes)
- [x] [Connected scatterplot](https://observablehq.com/@d3/connected-scatterplot/2)
- [ ] [Contours](https://observablehq.com/@d3/contours)
- [ ] [d3.packEnclose](https://observablehq.com/@d3/d3-packenclose)
- [x] [Density contours](https://observablehq.com/@d3/density-contours)
- [ ] [Difference chart](https://observablehq.com/@d3/difference-chart)
- [x] [Disjoint force-directed graph](https://observablehq.com/@d3/disjoint-force-directed-graph/2)
- [ ] [Diverging bar chart](https://observablehq.com/@d3/diverging-bar-chart)
- [ ] [Diverging stacked bar chart](https://observablehq.com/@d3/diverging-stacked-bar-chart)
- [x] [Donut chart](https://observablehq.com/@d3/donut-chart/2)
- [x] [Dot plot](https://observablehq.com/@d3/dot-plot/2)
- [x] [Force-directed graph](https://observablehq.com/@d3/force-directed-graph/2)
- [ ] [Force-directed tree](https://observablehq.com/@d3/force-directed-tree)
- [ ] [GeoTIFF contours](https://observablehq.com/@d3/geotiff-contours-ii)
- [ ] [Gradient encoding](https://observablehq.com/@d3/gradient-encoding)
- [ ] [Graticule labels](https://observablehq.com/@d3/graticule-labels-stereographic)
- [x] [Grouped bar chart](https://observablehq.com/@d3/grouped-bar-chart/2)
- [ ] [Hexbin (area)](https://observablehq.com/@d3/hexbin-area)
- [ ] [Hexbin map](https://observablehq.com/@d3/hexbin-map)
- [ ] [Hexbin](https://observablehq.com/@d3/hexbin)
- [ ] [Hierarchical bar chart](https://observablehq.com/@d3/hierarchical-bar-chart)
- [ ] [Hierarchical edge bundling](https://observablehq.com/@d3/hierarchical-edge-bundling)
- [x] [Hierarchical edge bundling](https://observablehq.com/@d3/hierarchical-edge-bundling/2)
- [x] [Histogram](https://observablehq.com/@d3/histogram/2)
- [ ] [Horizon chart](https://observablehq.com/@d3/horizon-chart)
- [x] [Horizontal bar chart](https://observablehq.com/@d3/horizontal-bar-chart/2)
- [x] [Icicle](https://observablehq.com/@d3/icicle/2)
- [ ] [Indented tree](https://observablehq.com/@d3/indented-tree)
- [x] [Index chart](https://observablehq.com/@d3/index-chart/2)
- [x] [Inline labels](https://observablehq.com/@d3/inline-labels/2)
- [ ] [Kernel density estimation](https://observablehq.com/@d3/kernel-density-estimation)
- [ ] [Line with missing data](https://observablehq.com/@d3/line-chart-missing-data/2)
- [ ] [Line chart with tooltip](https://observablehq.com/@d3/line-chart-with-tooltip)
- [ ] [Line chart](https://observablehq.com/@d3/line-chart/2)
- [ ] [Marimekko chart](https://observablehq.com/@d3/marimekko-chart)
- [ ] [Moving average](https://observablehq.com/@d3/moving-average)
- [ ] [Multi-line chart](https://observablehq.com/@d3/multi-line-chart)
- [ ] [Nested treemap](https://observablehq.com/@d3/nested-treemap)
- [ ] [Non-contiguous cartogram](https://observablehq.com/@d3/non-contiguous-cartogram)
- [ ] [Normal quantile plot](https://observablehq.com/@d3/normal-quantile-plot)
- [ ] [Normalized stacked area chart](https://observablehq.com/@d3/normalized-stacked-area-chart)
- [ ] [Orthographic to equirectangular](https://observablehq.com/@d3/orthographic-to-equirectangular)
- [x] [Circle packing](https://observablehq.com/@d3/pack/2)
- [ ] [Pannable chart](https://observablehq.com/@d3/pannable-chart)
- [ ] [Parallel coordinates](https://observablehq.com/@d3/parallel-coordinates)
- [ ] [Parallel sets](https://observablehq.com/@d3/parallel-sets)
- [x] [Pie chart](https://observablehq.com/@d3/pie-chart/2)
- [ ] [Projection comparison](https://observablehq.com/@d3/projection-comparison)
- [ ] [Q–Q plot](https://observablehq.com/@d3/q-q-plot)
- [ ] [Radial area chart](https://observablehq.com/@d3/radial-area-chart)
- [ ] [Radial dendrogram](https://observablehq.com/@d3/radial-dendrogram)
- [ ] [Radial stacked bar chart](https://observablehq.com/@d3/radial-stacked-bar-chart-ii)
- [ ] [Radial stacked bar chart](https://observablehq.com/@d3/radial-stacked-bar-chart)
- [x] [Radial tidy tree](https://observablehq.com/@d3/radial-tidy-tree/2)
- [ ] [Raster tiles](https://observablehq.com/@d3/raster-tiles)
- [ ] [Raster & vector](https://observablehq.com/@d3/raster-vector)
- [ ] [Realtime horizon chart](https://observablehq.com/@d3/realtime-horizon-chart)
- [ ] [Ridgeline (joy) plot](https://observablehq.com/@d3/ridgeline-plot)
- [x] [Sankey diagram](https://observablehq.com/@d3/sankey/2)
- [ ] [Scatterplot matrix](https://observablehq.com/@d3/scatterplot-matrix)
- [ ] [Scatterplot tour](https://observablehq.com/@d3/scatterplot-tour)
- [ ] [Scatterplot with shapes](https://observablehq.com/@d3/scatterplot-with-shapes)
- [ ] [Scatterplot](https://observablehq.com/@d3/scatterplot)
- [ ] [Seamless zoomable map tiles](https://observablehq.com/@d3/seamless-zoomable-map-tiles)
- [ ] [Slope chart](https://observablehq.com/@d3/slope-chart)
- [ ] [Smooth zooming](https://observablehq.com/@d3/smooth-zooming)
- [ ] [Sortable bar chart](https://observablehq.com/@d3/sortable-bar-chart)
- [ ] [Spike map](https://observablehq.com/@d3/spike-map)
- [x] [Stacked area chart](https://observablehq.com/@d3/stacked-area-chart/2)
- [x] [Stacked bar chart](https://observablehq.com/@d3/stacked-bar-chart/2)
- [x] [Stacked horizontal bar chart](https://observablehq.com/@d3/stacked-horizontal-bar-chart/2)
- [x] [Stacked normalized horizontal bar chart](https://observablehq.com/@d3/stacked-normalized-horizontal-bar/2)
- [ ] [Stacked-to-grouped bars](https://observablehq.com/@d3/stacked-to-grouped-bars)
- [ ] [State choropleth](https://observablehq.com/@d3/state-choropleth)
- [ ] [Streamgraph transitions](https://observablehq.com/@d3/streamgraph-transitions)
- [ ] [Streamgraph](https://observablehq.com/@d3/streamgraph/2)
- [ ] [Styled axes](https://observablehq.com/@d3/styled-axes)
- [ ] [Sunburst](https://observablehq.com/@d3/sunburst)
- [ ] [Temporal force-directed graph](https://observablehq.com/@d3/temporal-force-directed-graph)
- [ ] [Threshold encoding](https://observablehq.com/@d3/threshold-encoding)
- [ ] [Tidy tree](https://observablehq.com/@d3/tidy-tree)
- [ ] [Tissot’s indicatrix](https://observablehq.com/@d3/tissots-indicatrix)
- [ ] [Treemap](https://observablehq.com/@d3/treemap)
- [ ] [Variable-color line](https://observablehq.com/@d3/variable-color-line)
- [ ] [Vector field](https://observablehq.com/@d3/vector-field)
- [ ] [Vector tiles](https://observablehq.com/@d3/vector-tiles)
- [ ] [Versor dragging](https://observablehq.com/@d3/versor-dragging)
- [ ] [Voronoi labels](https://observablehq.com/@d3/voronoi-labels)
- [ ] [Web Mercator tiles](https://observablehq.com/@d3/web-mercator-tiles)
- [ ] [Word cloud](https://observablehq.com/@d3/word-cloud)
- [ ] [World choropleth](https://observablehq.com/@d3/world-choropleth)
- [ ] [World map](https://observablehq.com/@d3/world-map)
- [ ] [World tour](https://observablehq.com/@d3/world-tour)
- [ ] [Zoom to bounding box](https://observablehq.com/@d3/zoom-to-bounding-box)
- [ ] [Zoomable area chart](https://observablehq.com/@d3/zoomable-area-chart)
- [ ] [Zoomable bar chart](https://observablehq.com/@d3/zoomable-bar-chart)
- [ ] [Zoomable circle packing](https://observablehq.com/@d3/zoomable-circle-packing)
- [ ] [Zoomable icicle](https://observablehq.com/@d3/zoomable-icicle)
- [ ] [Zoomable sunburst](https://observablehq.com/@d3/zoomable-sunburst)
- [ ] [Zoomable treemap](https://observablehq.com/@d3/zoomable-treemap)

mbostock (to move to d3):

- [ ] [Slope chart](https://observablehq.com/@mbostock/cancer-survival-rates)
- [ ] [Electricity usage, 2019](https://observablehq.com/@mbostock/electric-usage-2019)
- [ ] [Epicyclic gearing](https://observablehq.com/@mbostock/epicyclic-gearing)
- [ ] [Global temperature trends](https://observablehq.com/@mbostock/global-temperature-trends)
- [ ] [Hertzsprung–Russell diagram](https://observablehq.com/@mbostock/hertzsprung-russell-diagram)
- [ ] [Icelandic population by age, 1841–2019](https://observablehq.com/@mbostock/icelandic-population-by-age-1841-2019)
- [ ] [Inequality in American cities](https://observablehq.com/@mbostock/inequality-in-american-cities)
- [ ] [Marey’s trains](https://observablehq.com/@mbostock/mareys-trains)
- [ ] [Methods of comparison, compared](https://observablehq.com/@mbostock/methods-of-comparison-compared)
- [ ] [Mobile patent suits](https://observablehq.com/@mbostock/mobile-patent-suits)
- [ ] [New zealand tourists, 1921–2018](https://observablehq.com/@mbostock/new-zealand-tourists-1921-2018)
- [ ] [Owls to the max](https://observablehq.com/@mbostock/owls-to-the-max)
- [ ] [Phases of the moon](https://observablehq.com/@mbostock/phases-of-the-moon)
- [ ] [Polar clock](https://observablehq.com/@mbostock/polar-clock)
- [ ] [Predator and prey](https://observablehq.com/@mbostock/predator-and-prey)
- [ ] [PSR B1919+21](https://observablehq.com/@mbostock/psr-b1919-21)
- [ ] [Revenue by music format, 1973–2018](https://observablehq.com/@mbostock/revenue-by-music-format-1973-2018)
- [ ] [Sea ice extent, 1978–2017](https://observablehq.com/@mbostock/sea-ice-extent-1978-2017)
- [ ] [Solar path](https://observablehq.com/@mbostock/solar-path)
- [ ] [Solar terminator](https://observablehq.com/@mbostock/solar-terminator)
- [ ] [Spilhaus shoreline map](https://observablehq.com/@mbostock/spilhaus-shoreline-map)
- [ ] [Star map](https://observablehq.com/@mbostock/star-map)
- [ ] [Stern–brocot tree](https://observablehq.com/@mbostock/stern-brocot-tree)
- [ ] [Tadpoles](https://observablehq.com/@mbostock/tadpoles)
- [ ] [The impact of vaccines](https://observablehq.com/@mbostock/the-impact-of-vaccines)
- [ ] [The wealth & health of nations](https://observablehq.com/@mbostock/the-wealth-health-of-nations)
- [ ] [Phylogenetic tree](https://observablehq.com/@mbostock/tree-of-life)
- [ ] [U.S. airports voronoi](https://observablehq.com/@mbostock/u-s-airports-voronoi)
- [ ] [U.S. population by state, 1790–1990](https://observablehq.com/@mbostock/u-s-population-by-state-1790-1990)
- [ ] [Voronoi stippling](https://observablehq.com/@mbostock/voronoi-stippling)
- [ ] [Walmart’s growth](https://observablehq.com/@mbostock/walmarts-growth)
- [ ] [World airports voronoi](https://observablehq.com/@mbostock/world-airports-voronoi)

fil (to move to d3):

- [ ] [Occlusion](https://observablehq.com/@fil/occlusion)

Others (to leave as-is):

- [Directly labelling lines](https://observablehq.com/@harrystevens/directly-labelling-lines)
- [Sequences sunburst](https://observablehq.com/@kerryrodden/sequences-sunburst)
- [Tangled tree visualization](https://observablehq.com/@nitaku/tangled-tree-visualization-ii)
- [World history timeline](https://observablehq.com/@tezzutezzu/world-history-timeline)
- [Centerline labeling](https://observablehq.com/@veltman/centerline-labeling)
- [Watercolor](https://observablehq.com/@veltman/watercolor)

**Comment by Fil** [comment]
Several of the “functional style” notebooks (now deprecated) are used in snippets. For instance, the treemap snippet creates two cells:

<img width="656" alt="Capture d’écran 2023-07-14 à 14 58 37" src="https://github.com/d3/d3/assets/7001/ec83a9a2-9bfe-4b10-9d9c-2808a629caa3">

<img width="1022" alt="Capture d’écran 2023-07-14 à 14 58 55" src="https://github.com/d3/d3/assets/7001/0dd697ea-b622-4c36-bed1-091a36a84209">

**Comment by Fil** [comment]
I think I'm done on this issue… until next time :)
