### ISSUE TITLE
restructure module READMEs (tracking issue)

### ISSUE THREAD

**Issue by Fil** [d3/d3#3775]
- [x] d3-array https://github.com/d3/d3-array/pull/279
- [x] d3-axis https://github.com/d3/d3-axis/pull/94
- [x] d3-brush https://github.com/d3/d3-brush/pull/103
- [x] d3-chord https://github.com/d3/d3-chord/pull/30
- [x] d3-color https://github.com/d3/d3-color/pull/119
- [x] d3-contour https://github.com/d3/d3-contour/pull/77
- [x] d3-delaunay https://github.com/d3/d3-delaunay/pull/143
- [x] d3-dispatch https://github.com/d3/d3-dispatch/pull/37
- [x] d3-drag https://github.com/d3/d3-drag/pull/94
- [x] d3-dsv https://github.com/d3/d3-dsv/pull/100
- [x] d3-ease https://github.com/d3/d3-ease/pull/37
- [x] d3-fetch https://github.com/d3/d3-fetch/pull/51
- [x] d3-force https://github.com/d3/d3-force/pull/221
- [x] d3-format https://github.com/d3/d3-format/pull/141
- [x] d3-geo https://github.com/d3/d3-geo/pull/286
- [x] d3-hierarchy https://github.com/d3/d3-hierarchy/pull/211
- [x] d3-interpolate https://github.com/d3/d3-interpolate/pull/115
- [x] d3-path https://github.com/d3/d3-path/pull/37
- [x] d3-polygon https://github.com/d3/d3-polygon/pull/38
- [x] d3-quadtree https://github.com/d3/d3-quadtree/pull/50
- [x] d3-random https://github.com/d3/d3-random/pull/50
- [x] d3-scale https://github.com/d3/d3-scale/pull/283
- [x] d3-scale-chromatic https://github.com/d3/d3-scale-chromatic/pull/49
- [x] d3-selection https://github.com/d3/d3-selection/pull/314
- [x] d3-shape https://github.com/d3/d3-shape/pull/210
- [x] d3-time-format https://github.com/d3/d3-time-format/pull/122
- [x] d3-time https://github.com/d3/d3-time/pull/67
- [x] d3-timer https://github.com/d3/d3-timer/pull/56
- [x] d3-transition https://github.com/d3/d3-transition/pull/145
- [x] d3-zoom https://github.com/d3/d3-zoom/pull/271
- [x] D3+API https://github.com/d3/d3/pull/3776

**Comment by Fil** [comment]
🙏
